src/Entity/Reservation.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
#[ApiResource]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateDebut = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $DateFin = null;

    #[ORM\Column]
    private ?int $NbNuit = null;

    #[ORM\Column(length: 255)]
    private ?string $Total = null;

    #[ORM\Column(length: 255)]
    private ?string $Statue = null;

    #[ORM\Column(length: 255)]
    private ?string $StatuePayment = null;

    #[ORM\ManyToOne(inversedBy: 'id_User')]
    private ?Annonce $idAnnonce = null;

    #[ORM\ManyToOne(inversedBy: 'id_user_reservation')]
    private ?User $idUser = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): self
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->DateFin;
    }

    public function setDateFin(\DateTimeInterface $DateFin): self
    {
        $this->DateFin = $DateFin;

        return $this;
    }

    public function getNbNuit(): ?int
    {
        return $this->NbNuit;
    }

    public function setNbNuit(int $NbNuit): self
    {
        $this->NbNuit = $NbNuit;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->Total;
    }

    public function setTotal(string $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getStatue(): ?string
    {
        return $this->Statue;
    }

    public function setStatue(string $Statue): self
    {
        $this->Statue = $Statue;

        return $this;
    }

    public function getStatuePayment(): ?string
    {
        return $this->StatuePayment;
    }

    public function setStatuePayment(string $StatuePayment): self
    {
        $this->StatuePayment = $StatuePayment;

        return $this;
    }

    public function getIdAnnonce(): ?Annonce
    {
        return $this->idAnnonce;
    }

    public function setIdAnnonce(?Annonce $idAnnonce): self
    {
        $this->idAnnonce = $idAnnonce;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(?User $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;


use Symfony\Component\Form\Extension\Core\Type\HiddenType;


class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('DateDebut',DateType::class,['attr' => ['class' => 'form-control date']])
        ->add('DateFin',DateType::class,['attr' => ['class' => 'form-control date']])
        ->add('NbNuit',IntegerType::class,['attr' => ['class' => 'form-control nb d-none','min' => 1,'value' => '0']])
        ->add('Total',IntegerType::class,['attr' => ['class' => '','min' => 1,'value' => '1']])
        ->add('Statue',HiddenType::class,['attr' => ['class' => 'd-none','value' => '0']])
        ->add('StatuePayment',HiddenType::class,['attr' => ['class' => 'disabled','min' => 0,'value' => '1']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Annonce;
use App\Entity\User;
use App\Entity\Reservation;
use App\Form\ReservationType;
use App\Repository\AnnonceRepository;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry as DoctrineManagerRegistry;

#[Route('/reservation')]
class ReservationController extends AbstractController
{
    #[Route('/', name: 'app_reservation_index', methods: ['GET'])]
    public function index(ReservationRepository $reservationRepository): Response
    {
        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservationRepository->findAll(),
        ]);
    }

    public function commande(ReservationRepository $reservationRepository, AnnonceRepository $annonceRepository, int $id): Response
    {
        $annonce = $annonceRepository->find($id);
        return $this->render('reservation/_commande.html.twig', [
            'reservations' => $reservationRepository->findBy(["idAnnonce"=>$annonce]),
        ]);
    }

    #[Route('/new', name: 'app_reservation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReservationRepository $reservationRepository, DoctrineManagerRegistry $doctrine): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        //add annonce
        $idannonce = $request->query->get('idannonce');

        $repository = $doctrine->getRepository(Annonce::class);
        $annonce = $repository->find($idannonce);
        $reservation->setIdAnnonce($annonce);

        //set user annonce 
        $repository2 = $doctrine->getRepository(User::class);
        $email = $this->getUser()->getUserIdentifier();
        $user = $repository2->findOneBy(array('email' => $email));
        $user->addIdUserReservation($reservation);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('annonce', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reservation_show', methods: ['GET'])]
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reservation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reservationRepository->save($reservation, true);

            return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form,
        ]);
    }
    #[Route('/{id}/accepte', name: 'app_reservation_accepte', methods: ['GET', 'POST'])]
    public function accepte(Request $request, Reservation $reservation, ReservationRepository $reservationRepository, EntityManagerInterface $em): Response
    {

        $reservation->setStatue(1);
        $em->flush();
        return $this->redirectToRoute('app_annonce_commande', [], Response::HTTP_SEE_OTHER);


    }
    #[Route('/{id}/annuller', name: 'app_reservation_annuler', methods: ['GET', 'POST'])]
    public function annuller(Request $request, Reservation $reservation, ReservationRepository $reservationRepository, EntityManagerInterface $em): Response
    {

        $reservation->setStatue(3);
        $em->flush();
        return $this->redirectToRoute('app_annonce_commande', [], Response::HTTP_SEE_OTHER);


    }

    #[Route('/{id}', name: 'app_reservation_delete', methods: ['POST'])]
    public function delete(Request $request, Reservation $reservation, ReservationRepository $reservationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $reservationRepository->remove($reservation, true);
        }

        return $this->redirectToRoute('app_reservation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservation/_commande.html.twig
{% block body %}
      <table class="table">
        {% for reservation in reservations %}
            <tr>   
    {% if reservation.statue == 0 %}
                {# <td>{{ reservation.idUser }}</td> #}
                <td>{{ reservation.DateDebut ? reservation.DateDebut|date('d-m-Y') : '' }}</td>
                <td>{{ reservation.DateFin ? reservation.DateFin|date('d-m-Y') : '' }}</td>
                <td>{{ reservation.NbNuit }}</td>
                <td>{{ reservation.Total }} € </td>
                <td>{% if reservation.StatuePayment == 1 %}<i class="bi bi-bag-fill"></i>{% else %}<i class="bi bi-bag-plus"></i>{% endif %}</td>
                <td>{% if reservation.Statue == 1 %}<i class="bi bi-bag-check"></i>{% elseif reservation.Statue == 2 %}<i class="bi bi-bag-x"></i>{% else %}<i class="bi bi-bag"></i>{% endif %}</td>
                <td>
                {% if reservation.Statue == 0 %}
                    <a class="btn btn-outline-success" href="{{ path('app_reservation_accepte', {'id': reservation.id}) }}">Accepter</a>
                   <a class="btn btn-outline-warning" href="{{ path('app_reservation_annuler', {'id': reservation.id}) }}">Refuser</a>
                {% endif %}
                {% if reservation.Statue == 1 %}
                    <a class="btn btn-outline-danger" href="{{ path('app_reservation_annuler', {'id': reservation.id}) }}">Refuser / Annulé</a>
                {% endif %}
                    
                    <a class="btn btn-outline-info" href="{{ path('app_reservation_show', {'id': reservation.id}) }}">Afficher</a>
                </td>
    {% endif %}

            </tr>
        {% else %}
            <tr>
                <td colspan="8">Pas de resultat</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('app_reservation_delete', {'id': reservation.id}) }}" onsubmit="etes vous sur de suprimer;">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn btn-outline-danger">Suprimer</button>
</form>

templates/reservation/_form.html.twig
<div class="container">
 
{{ render(controller(

    'App\\Controller\\AnnonceController::showannonce', {id: app.request.get('idannonce')

     }

)) }}
{{ form_start(form) }}



    <div class="d-none">
    {{ form_row(form.NbNuit) }}
    {{ form_row(form.Statue) }}
    {{ form_row(form.StatuePayment) }}
    {{ form_row(form.Total) }}
    </div>
    {{ form_widget(form) }}


    <div class="row row-cols-auto">
<div class="col">
Nombre 
</div>
<div class="col">
    <div id="nb">
    0
    </div>
    </div>

<div class="col">
    Nuit
    </div>

    </div>

<div class="row row-cols-auto">
<div class="col">
Total
</div>
<div class="col">
    <div id="TotalHT">
    0 
    </div> 
    </div>

<div class="col">
    € / HT
    </div>

    </div>
<div class="row row-cols-auto">
<div class="col">
Total
</div>
<div class="col">
    <div id="Total">
    0 
    </div> 
    </div>

<div class="col">
    € / tva incluse (20 %)
    </div>

    </div>
    <label for="statpay">Méthode de paiement</label>
    <select name="reservation[StatuePayment]" id="statpay">
      <option value="0">Paiement Plus tard</option>
      <option value="1">Paiement Par paypal</option>
      <option value="2">Paiement Par cheque ou espece</option>
    </select>



<div class="paypal" style="display:none;">
<div id="smart-button-container">
    <div style="text-align: center;" ><label for="description"> </label><input type="text" name="descriptionInput" id="description" maxlength="127" value="atipik"></div>
      <p id="descriptionError" style="visibility: hidden; color:red; text-align: center;">Please enter a description</p>
    <div style="text-align: center;"><label for="amount"> </label><input name="amountInput" type="number" id="amount" value="" ></div>
      <p id="priceLabelError" style="visibility: hidden; color:red; text-align: center;">Please enter a price</p>
    <div id="invoiceidDiv" style="text-align: center; display: none;"><label for="invoiceid"> </label><input name="invoiceid" maxlength="127" type="text" id="invoiceid" value="" ></div>
      <p id="invoiceidError" style="visibility: hidden; color:red; text-align: center;">Please enter an Invoice ID</p>
    <div style="text-align: center; margin-top: 0.625rem;" id="paypal-button-container"></div>
  </div>
  </div>


  
<br>
<div class="alert alert-danger" id='message' style="display:none;">
</div>
    <button class="btn btn-outline-success" id="success">{{ button_label|default('Reserver') }}</button>
  
  <script src="https://www.paypal.com/sdk/js?client-id=sb&enable-funding=venmo&currency=EUR" data-sdk-integration-source="button-factory"></script>
  <script>
  function initPayPalButton() {
    var description = document.querySelector('#smart-button-container #description');
    var amount = document.querySelector('#smart-button-container #amount');
    var descriptionError = document.querySelector('#smart-button-container #descriptionError');
    var priceError = document.querySelector('#smart-button-container #priceLabelError');
    var invoiceid = document.querySelector('#smart-button-container #invoiceid');
    var invoiceidError = document.querySelector('#smart-button-container #invoiceidError');
    var invoiceidDiv = document.querySelector('#smart-button-container #invoiceidDiv');

    var elArr = [description, amount];

    if (invoiceidDiv.firstChild.innerHTML.length > 1) {
      invoiceidDiv.style.display = "block";
    }

    var purchase_units = [];
    purchase_units[0] = {};
    purchase_units[0].amount = {};

    function validate(event) {
      return event.value.length > 0;
    }

    paypal.Buttons({
      style: {
        color: 'blue',
        shape: 'pill',
        label: 'paypal',
        layout: 'horizontal',
        
      },

      onInit: function (data, actions) {
        actions.disable();

        if(invoiceidDiv.style.display === "block") {
          elArr.push(invoiceid);
        }

        elArr.forEach(function (item) {
          item.addEventListener('keyup', function (event) {
            var result = elArr.every(validate);
            if (result) {
              actions.enable();
            } else {
              actions.disable();
            }
          });
        });
      },

      onClick: function () {
        if (description.value.length < 1) {
          descriptionError.style.visibility = "visible";
        } else {
          descriptionError.style.visibility = "hidden";
        }

        if (amount.value.length < 1) {
          priceError.style.visibility = "visible";
        } else {
          priceError.style.visibility = "hidden";
        }

        if (invoiceid.value.length < 1 && invoiceidDiv.style.display === "block") {
          invoiceidError.style.visibility = "visible";
        } else {
          invoiceidError.style.visibility = "hidden";
        }

        purchase_units[0].description = description.value;
        purchase_units[0].amount.value = amount.value;

        if(invoiceid.value !== '') {
          purchase_units[0].invoice_id = invoiceid.value;
        }
      },

      createOrder: function (data, actions) {
        return actions.order.create({
          purchase_units: purchase_units,
        });
      },

      onApprove: function (data, actions) {
        return actions.order.capture().then(function (orderData) {

          // Full available details
          console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));

          // Show a success message within this page, e.g.
          const element = document.getElementById('paypal-button-container');
          element.innerHTML = '';
          element.innerHTML = '<h3>Thank you for your payment!</h3>';

          // Or go to another URL:  actions.redirect('thank_you.html');
          
        });
      },

      onError: function (err) {
        console.log(err);
      }
    }).render('#paypal-button-container');
  }
  initPayPalButton();
  </script>
  
   
    <script>

var satpayement = document.querySelector('#statpay');
satpayement.addEventListener('change', () => {
if (satpayement.value == 1){
  var paypal = document.getElementsByClassName('paypal');
  paypal[0].style.display = 'block';
}
else{
  var paypal = document.getElementsByClassName('paypal');
  paypal[0].style.display = 'none';
}
});
 // paypal

/*
function add_15_prix(){
var selectElement = document.getElementById('annonce2_prix');
selectElement.value = selectElement.value * 1.15;
}

var input = document.getElementById('annonce2_prix');
input.onchange = function() {
  add_15_prix();
}
*/


function getDateDifference(date1, date2) {
  // On calcule la différence en milisecondes
  var diff = Math.abs(date1.getTime() - date2.getTime());
  // On calcule la différence en jours en divisant la différence en milisecondes par la longueur d'un jour en milisecondes
  var diffInDays = diff / (1000 * 60 * 60 * 24);
  return diffInDays;
}

const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

function numberToMonth(number) {
  return months[number - 1];
}
// console.log(numberToMonth(1));


function te(){
var debut_month_id = document.querySelector('#reservation_DateDebut_month').value;
var debut_day = document.querySelector('#reservation_DateDebut_day').value;
var debut_yaer = document.querySelector('#reservation_DateDebut_year').value;

var Fin_month_id = document.querySelector('#reservation_DateFin_month').value;
var Fin_day = document.querySelector('#reservation_DateFin_day').value;
var Fin_yaer = document.querySelector('#reservation_DateFin_year').value;

//var debut_month =numberToMonth(debut_month_id);
//var Fin_month =numberToMonth(Fin_month_id);

var debut_month =debut_month_id;
var Fin_month =Fin_month_id;

var date1 = new Date(debut_yaer, debut_month, debut_day);
var date2 = new Date(Fin_yaer, Fin_month, Fin_day);

var dateofmax = document.getElementById('dateofmax');
var dateofmin = document.getElementById('dateofmin');

var datejour=new Date();

// btn-outline-success
var btn_valide = document.getElementById('success');
var message = document.getElementById('message');

if(date1 > date2){
  message.style.display ="block";
  message.textContent ="La date n'est pas valide"; 
  btn_valide.disabled = true;
}
else if(dateofmax.textContent > date2 ){
  message.style.display ="block";
  message.textContent ="La date n'est plus disponible pour ce bien"; 
  btn_valide.disabled = true;
}
else if (dateofmin.textContent <= date1){
  message.style.display ="block";
  message.textContent ="La date n'est plus disponible pour ce bien"; 
  btn_valide.disabled = true;

}
else if(date1 <= datejour){
  message.style.display ="block";
  message.textContent ="La date est déjà passé"; 
  btn_valide.disabled = true;
}
else{
  message.style.display ="none";
message.textContent =""; 
btn_valide.disabled = false;
  
// console.log(getDateDifference(date1, date2)); // affiche 14

let difference = getDateDifference(date1, date2);
// console.log(difference);

var nb = document.querySelector('.nb');
nb.value = difference;
var nbid = document.querySelector('#nb');
nbid.textContent = difference;

var prix = document.querySelector('#prix').textContent;
// console.log(prix);
var reservation_Total = document.querySelector('#reservation_Total');
var Total = document.querySelector('#Total');
var TotalHT = document.querySelector('#TotalHT');
var paypal = document.querySelector('#amount');

var calcule = Math.round((difference * prix)*1.20);
var calculeht = Math.round((difference * prix));
reservation_Total.value = calcule;
Total.textContent = calcule;
TotalHT.textContent = calculeht;
paypal.value = calcule;

}
}



var selectElement = document.querySelector('#reservation_DateDebut_month');
selectElement.addEventListener('change', () => {
te();
});

var selectElement = document.querySelector('#reservation_DateDebut_day');
selectElement.addEventListener('change', () => {
te();
});
var selectElement = document.querySelector('#reservation_DateDebut_year');
selectElement.addEventListener('change', () => {
te();
});
var selectElement = document.querySelector('#reservation_DateFin_month');
selectElement.addEventListener('change', () => {
te();
});
var selectElement = document.querySelector('#reservation_DateFin_day');
selectElement.addEventListener('change', () => {
te();
});

var selectElement = document.querySelector('#reservation_DateFin_year');
selectElement.addEventListener('change', () => {
te();
});
</script>


{{ form_end(form) }}
</div>

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier reservation{% endblock %}

{% block body %}
    <h1>Modifier reservation</h1>

    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reservation_index') }}">retour</a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Vos reservation{% endblock %}
 
{% block body %}
  <div class="container" >
    <h1>Vos reservation</h1>
  <div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
        References
      </button>
      </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <div class="row">
        <div class="col-md-6">
        <u>Paiement</u>
        <div></div>
        <i class="bi bi-bag-fill"></i> Paiement par paypal
        <div></div>
        <i class="bi bi-bag-plus"></i> Paiement sur place
        <div></div>
        <i class="bi bi-bag-x"></i> Paiement refuser
        <div></div>
        <i class="bi bi-basket3"></i> Paiement en attente
        </div>
        <div class="col-md-6">
       <u>Statut de la réservation</u>
        <div></div>
        <i class="bi bi-bag-check"></i> Valider par le proprietaire
        <div></div>
        <i class="bi bi-bag-x"></i> Refuser par le proprietaire / Annulation de la reservation
        <div></div>
        <i class="bi bi-bag"></i> En attente par le proprietaire
        </div>
        </div>
      </div>
    </div>
  </div>
</div>
  
    <table class="table">
        <thead>
            <tr>
                <th>Date du debut</th>
                <th>Date de fin</th>
                <th>Nombre de Nuit</th>
                <th>Total</th>
                <th>Statut</th>
                <th>Statut du Paiement</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

        {% for reservation in reservations %}
            <tr>
            
    {% if app.user == reservation.idUser %}
                
                {# <td>{{ reservation.idUser }}</td> #}
                <td>{{ reservation.DateDebut ? reservation.DateDebut|date('d-m-Y') : '' }}</td>
                <td>{{ reservation.DateFin ? reservation.DateFin|date('d-m-Y') : '' }}</td>
                <td>{{ reservation.NbNuit }}</td>
                <td>{{ reservation.Total }} € </td>
                <td>{% if reservation.StatuePayment == 1 %}<i class="bi bi-bag-fill"></i>{% else %}<i class="bi bi-bag-plus"></i>{% endif %}</td>
                <td>{% if reservation.Statue == 1 %}<i class="bi bi-bag-check"></i>{% elseif reservation.Statue == 2 %}<i class="bi bi-bag-x"></i>{% else %}<i class="bi bi-bag"></i>{% endif %}</td>
                <td>
                    <a class='btn btn-success' href="{{ path('app_reservation_show', {'id': reservation.id}) }}">Afficher</a>
                    <a class="btn btn-outline-danger" href="{{ path('app_reservation_annuler', {'id': reservation.id}) }}">Annulé</a>
                </td>
    {% endif %}

            </tr>
        {% else %}
            <tr>
                <td colspan="8">Il n'y a pas de reservations enregistrées.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div> <!--end div container" -->

{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    {{ include('reservation/_form.html.twig') }}

    {# <a href="{{ path('app_reservation_index') }}">back to list</a> #}
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Date de Debut</th>
                <td>{{ reservation.DateDebut ? reservation.DateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date de Fin</th>
                <td>{{ reservation.DateFin ? reservation.DateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre de Nuit</th>
                <td>{{ reservation.NbNuit }}</td>
            </tr>
            <tr>
                <th>Total TTC</th>
                <td>{{ reservation.Total }}</td>
            </tr>
            <tr>
                <th>Statue</th>
                <td>{{ reservation.Statue }}</td>
            </tr>
            <tr>
                <th>Statue du Payment</th>
                <td>{{ reservation.StatuePayment }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_reservation_index') }}">Retour en arrière</a>

    <a class="btn btn-outline-danger" href="{{ path('app_reservation_annuler', {'id': reservation.id}) }}">Annulé</a>
{% endblock %}