src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Metadata\ApiResource;

#[ApiResource]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];


    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 25)]
    private ?string $telephone = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $recup_mdp = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $commentaire = null;

    #[ORM\OneToMany(mappedBy: 'idUser', targetEntity: DocumentProprietaire::class)]
    #[ORM\JoinColumn( nullable: true)]
    private Collection $documentProprietaires;

    #[ORM\OneToMany(mappedBy: 'idUser', targetEntity: Annonce::class)]
    #[ORM\JoinColumn( nullable: true)]
    private Collection $annonces;

    #[ORM\OneToMany(mappedBy: 'idUser', targetEntity: Reservation::class)]
    private Collection $id_user_reservation;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Name = null;


    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstname = null;

    #[ORM\Column]
    private ?int $status = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;



    public function __construct()
    {
        $this->documentProprietaires = new ArrayCollection();
        $this->annonces = new ArrayCollection();
        $this->id_user_reservation = new ArrayCollection();
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    

    public function getRecupMdp(): ?string
    {
        return $this->recup_mdp;
    }

    public function setRecupMdp(?string $recup_mdp): self
    {
        $this->recup_mdp = $recup_mdp;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    /**
     * @return Collection<int, DocumentProprietaire>
     */
    public function getDocumentProprietaires(): Collection
    {
        return $this->documentProprietaires;
    }

    public function addDocumentProprietaire(DocumentProprietaire $documentProprietaire): self
    {
        if (!$this->documentProprietaires->contains($documentProprietaire)) {
            $this->documentProprietaires->add($documentProprietaire);
            $documentProprietaire->setIdUser($this);
        }

        return $this;
    }

    public function removeDocumentProprietaire(DocumentProprietaire $documentProprietaire): self
    {
        if ($this->documentProprietaires->removeElement($documentProprietaire)) {
            // set the owning side to null (unless already changed)
            if ($documentProprietaire->getIdUser() === $this) {
                $documentProprietaire->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Annonce>
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonce $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces->add($annonce);
            $annonce->setIdUser($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonce $annonce): self
    {
        if ($this->annonces->removeElement($annonce)) {
            // set the owning side to null (unless already changed)
            if ($annonce->getIdUser() === $this) {
                $annonce->setIdUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getIdUserReservation(): Collection
    {
        return $this->id_user_reservation;
    }

    public function addIdUserReservation(Reservation $idUserReservation): self
    {
        if (!$this->id_user_reservation->contains($idUserReservation)) {
            $this->id_user_reservation->add($idUserReservation);
            $idUserReservation->setIdUser($this);
        }

        return $this;
    }

    public function removeIdUserReservation(Reservation $idUserReservation): self
    {
        if ($this->id_user_reservation->removeElement($idUserReservation)) {
            // set the owning side to null (unless already changed)
            if ($idUserReservation->getIdUser() === $this) {
                $idUserReservation->setIdUser(null);
            }
        }

        return $this;
    }



    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(?string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    
    
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email',TextType::class,['attr' => ['class' => 'form-control'],'label' => 'Mail'])
            ->add('password',TextType::class,['attr' => ['class' => 'form-control'],'label' => 'Mot de passe'])
            ->add('telephone',TextType::class,['attr' => ['class' => 'form-control'],'label' => 'Telephone'])
            ->add('adresse',TextType::class,['attr' => ['class' => 'form-control'],'label' => 'Adresse'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\EmailType;
use App\Form\User1Type;
use App\Security\EmailVerifier;
use App\Form\RegistrationFormType;
use App\Form\TokenType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Mime\Email;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher;

#[Route('/user')]
class UserController extends AbstractController
{

    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }
    #[Route('/attente', name: 'app_user_attente')]
    public function proprietaireattente(UserRepository $userRepository): Response
    {
        return $this->render('user/propietaireattente.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }
    

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository, UserPasswordHasherInterface $userPasswordHasher,): Response
    {
        $user = new User();
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $userRepository->save($user, true);
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            return $this->redirectToRoute('app_document_proprietaire_new', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('/register.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/proprietaire', methods: ['GET', 'POST'])]
    public function addProprietaire(Request $request, UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager,EmailVerifier $emailVerifier, MailerInterface $mailer): Response
    {
        $user = new User();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $user->setRoles(["ROLE_PRO"]);
            $user->setStatus(0);
            $entityManager->persist($user);
            $entityManager->flush();
            // do anything else you need here, like send an email
            // generate a signed url and email it to the user
            $emailVerifier->sendEmailConfirmation('app_verify_email', $user,
                (new TemplatedEmail())
                    ->from(new Address('atipikhouse@dev3-g3-lz-es-zt-fb.go.yj.fr', 'AtipikHouse'))
                    ->to($user->getEmail())
                    ->subject('Please Confirm your Email')
                    ->htmlTemplate('registration/confirmation_email.html.twig')
            );

            $email = (new Email())
            ->from('atipikhouse@dev3-g3-lz-es-zt-fb.go.yj.fr')
            ->to('atipikdev3g3@gmail.com')
            ->subject('Nouvelle créé')
            ->html("<p>Vous avez créé votre compte AtipikHouse</br>Si ce compte n'a pas été créé par vous, veuillez nous contacter à <a href='mailto:atipikdev3g3@gmail.com'>atipikdev3g3@gmail.com</a>, et nous serons heureux de vous aider.</br>Pour rappel, penser à ajouter les documents nécessaire pour validé votre compte proprietaire.<br>.Pour cela utiliser le lien suivant : <a href='dev3-g3-lz-es-zt-fb.go.yj.fr/document/new'>Documents</a></br> ou en vous connectant sur <a href='dev3-g3-lz-es-zt-fb.go.yj.fr'>AtipikHouse</a> puis allez dans la rebrique document sur votre profile. </br>Bien à vous,</br>AtipikHouse");

            $mailer->send($email);

            return $this->redirectToRoute('home');
        }
        return $this->render('registration/register.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository): Response
    {
        $form = $this->createForm(User1Type::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'form' => $form,
        ]);
    }
    
    #[Route('/{id}/active', name: 'app_user_active', methods: ['GET', 'POST'])]
    public function active(Request $request, User $user, UserRepository $userRepository, EntityManagerInterface $em, MailerInterface $mailer): Response
    {

        $user->setStatus(1);
        $em->flush();
        $email = (new Email())
                ->from('atipikhouse@dev3-g3-lz-es-zt-fb.go.yj.fr')
                ->to($user->getEmail())
                //->cc('cc@example.com')
                //->bcc('bcc@example.com')
                //->replyTo('fabien@example.com')
                //->priority(Email::PRIORITY_HIGH)
                ->subject('Compte Propriétaire activé')
                ->html('<p>Votre compte a été activé.</br>Allez sur le site <a href="dev3-g3-lz-es-zt-fb.go.yj.fr">AtipikHouse</p></br></br>Bien à vous,</br>AtipikHouse');
        $mailer->send($email);
        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);


    }
    #[Route('/{id}/desactive', name: 'app_user_desactive', methods: ['GET', 'POST'])]
    public function desactive(Request $request, User $user, UserRepository $userRepository, EntityManagerInterface $em): Response
    {

        $user->setStatus(3);
        $em->flush();
        return $this->redirectToRoute('app_logout', [], Response::HTTP_SEE_OTHER);


    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Etes vous sur de suprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-outline-danger">Supprimer</button>
</form>

templates/user/_emailcheck.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/user/_passwordforget.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/user/_token.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-outline-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier compte utilisateur{% endblock %}

{% block body %}
    <h1>Modifier compte utilisateur</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}


    <a class="btn btn-outline-info" href="javascript:history.back()">Quitter</a>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Utilisateurs{% endblock %}

{% block body %}
{% if app.user and app.user.roles[0] == 'ROLE_ADMIN' %}


    <h1>Utilisateurs</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Telephone</th>
                <th>Status</th>
                <th>Commentaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.email }}</td>
                {# <td>{{ user.roles ? user.roles|json_encode : '' }}</td> #}
                <td>{{ user.telephone }}</td>
                <td>{% if user.status == 1 %}Activer{% elseif user.status == 3 %}Bloquer{% else %}compte suspendue{% endif %}</td>
                <td>{{ user.commentaire }}</td>
                <td>
                {% if user.status == 3 or user.status == 0 %}
                    <a class="btn btn-outline-success" href="{{ path('app_user_active', {'id': user.id}) }}">active</a>
                    {% else %}
                    <a class="btn btn-outline-success" href="{{ path('app_user_desactive', {'id': user.id}) }}">desactive</a>
                {% endif %}
                    <a class="btn btn-outline-info" href="{{ path('app_user_show', {'id': user.id}) }}">Afficher</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">Pas d'utilisateur</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endif %}
{% endblock %}

templates/user/motdepasseoublier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mot de passe oublier{% endblock %}

{% block body %}
<div class="m-2"></div>
<div class="container">
Mot de passe oublié
{{ include('user/_emailcheck.html.twig') }}
<br>
Si vous avez oublié votre mot de passe merci d'envoyer un mail à l'admin il vous fournira dans les plus brefs de laits
<br>
<a href="mailto:admin@atipik.com">admin@atipik.com</a>
</div>
<div class="m-2"></div>
  {% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}creation de compte{% endblock %}

{% block body %}
    <h1>Creation de compte</h1>

    {{ include('user/_form.html.twig') }}

    <a class="btn btn-outline-dark" href="{{ path('app_user_index') }}">< Retour en arrière</a>
{% endblock %}

templates/user/password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réinitialisation de mot de passe {% endblock %}

{% block body %}
    <h1>Réinitialisation de votre mot de passe</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}
        <button class="btn btn-outline-success">{{ button_label|default('Sauvegarder') }}</button>
    {{ form_end(form) }}

    <a class="btn btn-outline-dark" href="{{ path('app_user_index') }}">< Retour en arrière</a>
{% endblock %}

templates/user/propietaireattente.html.twig
{% extends 'base.html.twig' %}


{% block title %}Compte proprietaire a activer{% endblock %}

{% block body %}
{% if app.user and app.user.roles[0] == 'ROLE_ADMIN' %}

    <h1>Compte proprietaire a activer</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Email</th>
                <th>Telephone</th>
                <th>Status</th>
                <th>Adresse</th>
                <th>Commentaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            {% if user.status == 0 %}
                <tr>
                    <td>{{ user.email }}</td>
                    <td>{{ user.telephone }}</td>
                    <td>{% if user.status == 0 %}A activer{% else %}Activer{% endif %}</td>
                    <td>{{ user.adresse }}</td>
                    <td>{{ user.commentaire }}</td>
                    <td>
                        <a class="btn btn-outline-success" href="{{ path('app_user_active', {'id': user.id}) }}">active</a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('app_user_new') }}">Create new</a> #}
{% endif %}
{% endblock %}

templates/user/proprietaire.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creation utilisateurs{% endblock %}

{% block body %}
    <h1>Creation utilisateurs</h1>

    {{ include('register.html.twig') }}

    <a href="{{ path('app_user_index') }}">retour en arrière</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
{% if app.user %}

    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ user.telephone }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ user.status }}</td>
            </tr>
            <tr>
                <th>Recup_mdp</th>
                <td>{{ user.recupMdp }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adresse }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ user.commentaire }}</td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-info" href="{{ path('app_user_index') }}">< Retour en arrière</a>

    <a class="btn btn-warning" href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>

    {{ include('user/_delete_form.html.twig') }}
{% endif %}
{% endblock %}

templates/user/token.html.twig
{% extends 'base.html.twig' %}

{% block title %}Code de réinitialisation{% endblock %}

{% block body %}
<div class="m-2"></div>
<div class="container">
Mot de passe oublié
{{ include('user/_token.html.twig') }}

<br>
Si vous avez oublié votre mot de passe merci d'envoyer un mail à l'admin il vous fournira dans les plus brefs de laits
<br>
<a href="mailto:admin@atipik.com">admin@atipik.com</a>
</div>
<div class="m-2"></div>
  {% endblock %}